---
- hosts: jenkins
  vars_files:
    - vars.yml
  tasks:
    - name: Create user
      user:
        name: "{{ user.name }}"
        create_home: yes
        groups: sudo
        append: yes
    - name: Set home folder
      set_fact:
        home: "/home/{{ user.name }}"

    - name: Create home folder structure
      file:
        path: "{{ home }}/{{ item }}"
        state: directory
      with_items:
        - "{{ home_folders.tools_folder }}"
        - "{{ home_folders.additional_folders }}"

    - name: Add private ssh key
      copy:
        src: vault/vps_rsa
        dest: "/home/{{ user.name }}/.ssh/id_rsa"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "500"
    - name: Add public ssh key
      copy:
        src: vault/vps_rsa.pub
        dest: "/home/{{ user.name }}/.ssh/id_rsa.pub"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"


    - name: Install useful packages
      apt:
        pkg: "{{ packages }}"
        state: present
      become: true

    - name: Setup dotfiles
      block:
        - name: Clone the dotfiles repo
          git:
            repo: "{{ dotfiles_url }}"
            dest: "{{ home }}/.local/dotfiles"
            update: false
          register: dotfiles
        - name: Deploy dotfiles
          shell: "{{ home }}/.local/dotfiles/scripts/deploy.sh"
          when: dotfiles.changed
      tags: dotfiles

    - name: Setup private dotfiles
      block:
        - name: Clone the private dotfiles repo
          git:
            repo: "{{ private_dotfiles_url }}"
            dest: "{{ home }}/.local/utils"
            update: false
          register: private_dotfiles
        - name: Deploy dotfiles
          shell: "{{ home }}/.local/utils/laptop/deploy.sh"
          when: private_dotfiles.changed
      tags: dotfiles, private
